name: developer tests
on:
  - pull_request

jobs:
  jest:
    name: Developer tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
      - run: echo yes
      # - uses: actions/upload-artifact@v4 # upload test results
      #   if: success() || failure() # run this step even if previous step failed
      #   with:
      #     name: test-results
      #     path: jest-junit.xml
